### ISSUE TITLE
"LEVEL n" and "PRESS A KEY" color changes

### ISSUE THREAD

**Issue by nippur72** [Fabrizio-Caruso/CROSS-LIB#137]
the `LEVEL n` and `PRESS A KEY` text color sometimes is red, some other times is white; I guess depending on the last thing print before.

**Comment by Fabrizio-Caruso** [comment]
Yes, @nippur72, I am aware of this bug.

**Comment by Fabrizio-Caruso** [comment]
Fixed after a very long time.
