### ISSUE TITLE
Wish: how about some CP/M executables ?

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [Fabrizio-Caruso/CROSS-LIB#268]
Your code can be compiled on an impressive number of old platforms.

CP/M was an early system that allowed the same binary executable to work on a number of machines sporting a 8080 or above (especially Z80) CPU.

It would be "fun" if you included CP/M in your targets.

**Comment by Fabrizio-Caruso** [comment]
You have not looked at the list of targets. I have several CP/M targets in all possible flavors.
Take a look at:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/docs/STATUS.md

I support generic CP/M with all terminals types and I also support specific CP/M targets with software sprites with several brands and disk/binary formats.

**Comment by Fabrizio-Caruso** [comment]
@fidergo-stephane-gourichon if you want a specific binary for a specific target and you can't find it, let me know.

**Comment by Fabrizio-Caruso** [comment]
@fidergo-stephane-gourichon the way I support both graphics and non-graphics target is through Cross-lib tiles, which are a sort of virtual tiles. They are mapped to different things depending on the target, sub-target or options.
So my games come with tiles mapped to real graphics objects (inside the /games/xxx/tiles or mapped to specific ASCII characters.
For targets like generic CP/M, Commodore Pet, Commodore CBM 610 and many more the tile is just an ASCII/PETSCII/ATASCII/... character..
For targets with graphics including lots of CP/M targets (e.g., Epson HX-40, HX-80, etc.) a tile can be a sprite or a redefined character.
The game code is totally agnostic of these details.
The magic is done my C macros and by my Python scripts that create target-specific graphics assets.

**Comment by Fabrizio-Caruso** [comment]
@fidergo-stephane-gourichon Some dozens CP/M executales are in the release section )https://github.com/Fabrizio-Caruso/CROSS-LIB/releases). More can be built.

**Comment by fidergo-stephane-gourichon** [comment]
> You have not looked at the list of targets. I support several CP/M targets in all possible flavors.
> Take a look at:
> https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/docs/STATUS.md
> 
> I support both generic CP/M with all terminals types (ADM3A/VT52/VT100) and several specific CP/M targets even with software sprites that use specific graphics cards and/or sound chips.
> I support both plain Intel 8080/85 CP/M and Zilog 80 targets.

Thanks for your reply and explanations. Impressive work.
