### ISSUE TITLE
Sam Coupé version: Z88DK significant update.

### ISSUE THREAD

**Issue by dandoore** [Fabrizio-Caruso/CROSS-LIB#269]
There has been a large amount of work in Z88DK for SAM in the last weeks: https://github.com/z88dk/z88dk/wiki/Platform--Sam-Coupe.md with support for graphics, high colour modes and eTracker music - can CROSS-LIB be updated for the new capabilites?

**Comment by Fabrizio-Caruso** [comment]
Hi! Yes, definitely and I will update it. I always try to catch up with the latest updates on the several cross compilers I depend on.

**Comment by dandoore** [comment]
Cool, be nice to ditch the ansi graphics :)

**Comment by Fabrizio-Caruso** [comment]
I have not forgotten this one... I will do it. I just need to sort out a few other things before I move on improving the target-specific support.

**Comment by dandoore** [comment]
> I have not forgotten this one... I will do it. I just need to sort out a few other things before I move on improving the target-specific support.

Awesome, thanks for the update :)

**Comment by Fabrizio-Caruso** [comment]
I have implemented graphics and sounds for the sam coupe on all 5 games:

Cross Horde: https://github.com/Fabrizio-Caruso/CROSS-LIB/releases/download/XHorde1.0/Xhorde_samcoupe.dsk
Cross Snake: https://github.com/Fabrizio-Caruso/CROSS-LIB/releases/download/XSnake2.0/Xsnake_samcoupe.dsk
Cross Bomber: https://github.com/Fabrizio-Caruso/CROSS-LIB/releases/download/XBomber/Xbomber_samcoupe.dsk
Cross Shoot: https://github.com/Fabrizio-Caruso/CROSS-LIB/releases/download/XShootRebuild/Xshoot_samcoupe.dsk
Cross Chase: https://github.com/Fabrizio-Caruso/CROSS-LIB/releases/download/XChase/Xchase_samcoupe.dsk
