### ISSUE TITLE
add some drawing primitives like lines, rects and circles

### ISSUE THREAD

**Issue by eadmaster** [Fabrizio-Caruso/CROSS-LIB#274]
These could be useful as alternative to titles and to render some effects:
e.g.:
````
_XL_DRAW_LINE(X1, Y1, X2, Y2, C)
_XL_DRAW_RECT(X1, Y1, X2, Y2, C)
````

**Comment by eadmaster** [comment]
no need, i think i've understood your point...

Btw i've found this library  actually providing some form of abstractions of these drawing primitives:
https://github.com/spotlessmind1975/midres

Unfortunately it does not support any console.

**Comment by Fabrizio-Caruso** [comment]
@eadmaster midres stands for MIDdle RESolution. So it is also tile-based and so you still get 2x2 or slightly higher low or mid resolution. Midres is more performance oriented than Cross Lib, whereas Cross Lib aims at covering *all* targets including very exotic ones and targets with exotic CPUs such as the RCA 1802.

For pixel drawing primitives you should look at TGI (for 6502-based) targets and Z88DK lib for (for Z80-based targets).

You find me on FB, just in case you want to ask me questions.

**Comment by eadmaster** [comment]
aren't these the primitives i was suggesting?
https://github.com/spotlessmind1975/midres/blob/master/src/midres.h#L486

Thank you for pointing me to TGI btw, i will take a look at it!

**Comment by Fabrizio-Caruso** [comment]
@eadmaster as fas as I know, midres is a tile-based library for some Z80 and MOS6502 targets. 
I am not the author. The author (another Italian by the way) can answer your questions.
