### ISSUE TITLE
MO5/TO7 f2k5.exe is not running on Cygwin

### ISSUE THREAD

**Issue by christopheKohler** [Fabrizio-Caruso/CROSS-LIB#280]
The current compiled version require a dll that is not present in latest cygwin. ( cyggcc_s-1.dll )
Getting source code of the tool and recompiling it solved the issue.

**Comment by Fabrizio-Caruso** [comment]
Thanks for reporting this issue. Indeed I should do the same in an automatic way.
This is going to be a feature request.

**Comment by christopheKohler** [comment]
Got same problem with tool gamate-fixcart.exe. It was crashing on my PC. I had to recompile it (gcc gamate-fixcart.c)

**Comment by Fabrizio-Caruso** [comment]
@christopheKohler Thanks! 
I will implement a new `xl` command to build all the tools that can be built from source.

**Comment by Fabrizio-Caruso** [comment]
I have implemented `xl tools` (or equivalently `xl build tools`) to build these tools.
I will add more tools in the future.
This should fix this issue.
Could you please let me know if it works for you?

**Comment by Fabrizio-Caruso** [comment]
Other buildable tools may be:
- exomixer (currently only used by c64)
- c1541 (currently only used by c128 with Z80)
- srec_cat (used by osic1p)
- file2dsk (coco/dragon)
- sapfs (mo5 and to7)
- nocart (cpc)
- ubbinrtap (microbee)
- makewzd (oz)
- dosgen (abc80/800)
- doscopy (abc80/800)
- bin2bac2 (abc80/800)
- bin2abc (abc80)
- m20 (Olivetti M20)

**Comment by Fabrizio-Caruso** [comment]
I am going to track this as a feature request.
