### ISSUE TITLE
"./xl build chase zx81" errors

### ISSUE THREAD

**Issue by christopheKohler** [Fabrizio-Caruso/CROSS-LIB#282]
I also tried with 1 thread, same result.

`$ ./xl build chase z88dk_targets 1
Cross-Lib `xl` helper script
Platform: cygwin
GNU MAKE command: make

Project name       : chase
Project type       : game
Number of threads  : 1
Extra optimization :
Compiler's options :
run command : make z88dk_targets ZSDCC_MAKEFILE_THREADS_OPTS='-j 1' ZSDCC_MAKEFILE_COMPILATION_OPTS= -f games/chase/Makefile.chase

zcc.exe +ace -DFORCE_NARROW -D_DEFAULT_ASCII -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/pet -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Igames/chase/generated_assets -Igames/chase \
-D__ACE__ -DFULL_GAME -DBETWEEN_LEVEL -DEND_SCREEN \
-DSOUNDS \
-DCONIO \
-clib=default \
-DUDG_GRAPHICS \
-DANIMATE_PLAYER \
cross_lib/display/init_graphics/z88dk/udg/udg_init_graphics.c \
games/chase/generated_assets/z88dk_xchase.asm \
games/chase/end_screen.c \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c cross_lib/text/text_macros.c games/chase/move_player.c games/chase/ghost.c  games/chase/level.c games/chase/character.c games/chase/game_text.c games/chase/main.c games/chase/init_images.c games/chase/strategy.c games/chase/item.c games/chase/skull.c games/chase/bullet.c   games/chase/horizontal_missile.c games/chase/rocket.c  \
-o ace -Cz--audio -create-app
cp ace.wav ../build/Xchase_ace_exp_16k.wav
cp ace.tap ../build/Xchase_ace_exp_16k.tap
rm ace.wav
rm ace.tap
rm ace
zcc.exe +c128 -compiler=sdcc -SO3  -DFORCE_NARROW -D_DEFAULT_ASCII \
-Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/pet -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Igames/chase/generated_assets -Igames/chase -DEXTRA_TITLE \
-lndos -subtype=disk \
-D__C128_Z80__ -DXSize=40 \
-DSOUNDS \
-DFORCE_BIT_BANG \
-DFULL_GAME -DEND_SCREEN -DNO_BLINKING \
-DFORCE_CONIO_LIB \
-DCONIO -DNO_INIT_GRAPHICS \
games/chase/end_screen.c \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c cross_lib/text/text_macros.c games/chase/move_player.c games/chase/ghost.c  games/chase/level.c games/chase/character.c games/chase/game_text.c games/chase/main.c games/chase/init_images.c games/chase/strategy.c games/chase/item.c games/chase/skull.c games/chase/bullet.c   games/chase/horizontal_missile.c games/chase/rocket.c  \
-create-app -oa40.bin
cannot open peep rule file
copt: can't open patterns file
make: *** [games/chase/makefiles.chase/makefiles_z88dk/Makefile_z88dk_a-k:492: c128_z80_40col] Error 1

**Comment by christopheKohler** [comment]
Seem machine ZX81 is causing this problem.

**Comment by Fabrizio-Caruso** [comment]
@christopheKohler Which Z88DK version are you using? Did you install it from a snapshot or did you recompile it from source? If so, did you enable SDCC?

**Comment by christopheKohler** [comment]
ok found the problem. I deleted the directory
c:\z88dk\libsrc\_DEVELOPMENT\
And this is required.

**Comment by christopheKohler** [comment]
Updating to the latest nightly build, I got that error : 

Error: library file 'c:/z88dk/lib/clibs/ndos.lib' version 16, expected version 14
Error: library file 'c:/z88dk/lib/clibs/cpc_clib.lib' version 16, expected version 14
Error: library file 'c:/z88dk/lib/clibs/z80_crt0.lib' version 16, expected version 14

**Comment by christopheKohler** [comment]
Back on officiel release (z88dk-win32-2.1.zip) , got now that error : 

Error at file 'games/chase/end_screen.c' line 766: syntax error
Error at file 'games/chase/end_screen.c' line 782: syntax error
Error at file 'games/chase/end_screen.c' line 784: syntax error
Error at file 'games/chase/end_screen.c' line 785: syntax error
Error at file 'games/chase/end_screen.c' line 791: syntax error
Error at file 'games/chase/end_screen.c' line 792: syntax error
Error at file 'games/chase/end_screen.c' line 828: syntax error
Error at file 'games/chase/end_screen.c' line 829: syntax error
Error at file 'games/chase/end_screen.c' line 839: syntax error
Error at file 'games/chase/end_screen.c' line 921: syntax error
Errors in source file games/chase/end_screen.c:
Error at file 'games/chase/end_screen.c' line 766: syntax error
Error while reading string from D:\Dev\Cygwin64\tmp\zcc00003CACCC0E2.err

**Comment by christopheKohler** [comment]
Note that horde and bomber are compiling fine for zx81. The 3 others games have errors (not the same). So guess this is only code update to do.

**Comment by Fabrizio-Caruso** [comment]
If you delete `c:\z88dk\libsrc_DEVELOPMENT`, you break newlib... which I am probably not using.

You need:
http://nightly.z88dk.org/z88dk-win32-20220311-c8d2246b6-19435.zip

and follow these instructions:
https://github.com/z88dk/z88dk/wiki/installation
(i.e., just set a couple of environment variable in Windows, not in Cygwin)

Have you done this?

I do not have this problem.

**Comment by Fabrizio-Caruso** [comment]
@christopheKohler could you plese tell me if you are still getting this problem?
I am not able to reproduce it.

**Comment by christopheKohler** [comment]
I've done all settings. (using same nightly as mentionned)

chase have this error : ( ./xl build chase zx81 )

games/chase/end_screen.c:841: error: syntax error
  ^---- SECTION DABS (ABS)
games/chase/end_screen.c:857: error: syntax error
  ^---- _dance::
games/chase/end_screen.c:859: error: syntax error
  ^---- ld l, 4 (ix)
games/chase/end_screen.c:862: error: syntax error
  ^---- ld h, 5 (ix)
games/chase/end_screen.c:869: error: syntax error
  ^---- ld c, 4 (ix)
games/chase/end_screen.c:870: error: syntax error
  ^---- ld b, 5 (ix)
games/chase/end_screen.c:909: error: syntax error
  ^---- ld l, 4 (ix)
games/chase/end_screen.c:912: error: syntax error
  ^---- ld h, 5 (ix)
games/chase/end_screen.c:924: error: syntax error
  ^---- _gameCompleted::
games/chase/end_screen.c:1006: error: syntax error
  ^---- SECTION CABS (ABS)

**Comment by christopheKohler** [comment]
Disabling sdcc and chase can compile.

**Comment by Fabrizio-Caruso** [comment]
As we have verified together this is a problem with your setup:
Cygwin 64-bit with Z88DK 32-bit snapshot, which has broken ZSDCC

This bug is in Z88DK (or it is just not supported). 
I have opened a ticket for this:
https://github.com/z88dk/z88dk/issues/1992
