### ISSUE TITLE
[z88dk-zsdcc] - testing v4.3.0

### ISSUE THREAD

**Issue by feilipu** [Fabrizio-Caruso/CROSS-LIB#285]
Fabrizio,

as part of testing `sdcc` v4.3.0, we're possibly going to replace the sdcc pre-processor with `ucpp`, the same one currently used by `scc80`.

The new sdcc pre-processor for v4.3.0 is based on `gcpp-12` and it is currently not usable. For v4.2.0 (currently used by z88dk) it is based on `gcpp-4`.

Moving to `ucpp` for both compilers for z88dk would set up a limit of C99 as the standard compliance in the future.

Could you please build / test against your CROSS-LIB to see whether you encounter any issues with the new `zsdcc` (draft r13854) or using `ucpp` (C99 standard)? Using the current draft PR https://github.com/z88dk/z88dk/pull/2190.

I'd be very happy to be able to pass feedback to the sdcc team, or you can raise it directly with them if you prefer.

P.

**Comment by Fabrizio-Caruso** [comment]
Sorry for my very late reply. Is this still valid? I see that now Z88DK partially supports a third compiler (clang). Can you provide a Windows binary and exact instructions on what I need to do to run the compiler?

**Comment by feilipu** [comment]
I think @suborb has made a set of binaries, and the request is still valid. But there's some bug fixes already flowed upstream which this doesn't have.

Still worth testing though.

**Comment by Fabrizio-Caruso** [comment]
@suborb, if you want, I can run some tests if I understand how to do it and where to get the binaries.

**Comment by feilipu** [comment]
Actually, just noted that 4.3.0 has been released already. I've been AFK for nearly a month.

So there's no point to do further with this. I'll close it.
