### ISSUE TITLE
No known emulator

### ISSUE THREAD

**Issue by EtchedPixels** [Fabrizio-Caruso/CROSS-LIB#286]
My EmulatorKit emulates RC2014 and SC126 if you still need emulations. The RC2014 emulation can also emulate the EF9345 and TMS9918A graphics to some extent. TMS9918A needs sprites debugging yet.

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot for letting me know. I will definitely give it a try. I would make testing my library possible on more targets.

**Comment by danboid** [comment]
Hi Mr Cox!
