### ISSUE TITLE
How to build for the Sega SG 1000?

### ISSUE THREAD

**Issue by Hexadigital** [Fabrizio-Caruso/CROSS-LIB#287]
Hello Fabrizio!

What is the process for building the games for the SG 1000? It doesn't look like sg1000 has any build rules inside of Makefile_common.

**Comment by Fabrizio-Caruso** [comment]
Hi! Thanks for showing interest in my project and games!

There is an ugly way to build any of the about 200 targets I support but indeed it is easy only for about the 50 that are in Makefile_common.
There is an old Makefile inside src/games/chase that can be used but it is not convenient and it would require some minimum work.

I am now adding SC3000 and SG1000 in Makefile_common to make it super easy to build with the xl script:
xl <game> sg1000 -> build <game> for SG1000
or
xl games sg1000 -> build all 6 games for SG1000

Once I am done, could you please test the games and let me know if they work well and at an acceptable speed (not too slow, not too fast)?

I still need to tune the speed for each game on the SC3000/SG1000.

**Comment by Fabrizio-Caruso** [comment]
On the SG1000, Snake, Shuriken and Shoot do not work, yet, because of the limited RAM.
I need to test them on the SC3000 but I need a basic cartridge file...

**Comment by Fabrizio-Caruso** [comment]
@Hexadigital I am closing this issue. I think it is ok (except for the limitations of the RAM on the SG1000).

**Comment by Hexadigital** [comment]
Sorry for the late reply, and thank you very much!
